# Generated by Django 4.0.6 on 2022-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaoSocial', models.CharField(max_length=200)),
                ('nomeFantasia', models.CharField(max_length=120)),
                ('cnpj', models.PositiveIntegerField(blank=True)),
                ('telefone', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=80)),
                ('logo', models.ImageField(upload_to='emp_imgs/')),
                ('cep', models.PositiveIntegerField(blank=True)),
                ('tipoCep', models.CharField(max_length=20)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=80)),
                ('bairro', models.CharField(max_length=140)),
                ('endereco', models.CharField(max_length=140)),
                ('complemento', models.CharField(max_length=190)),
            ],
        ),
    ]
